//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _91APPTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderList
    {
        public string orderId { get; set; }
        public string orderItem { get; set; }
        public int price { get; set; }
        public int cost { get; set; }
        public int status { get; set; }
    }
}
